<!DOCTYPE html>
<html lang="ja">

<head>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-143164157-1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-143164157-1');
    </script>
    


    <!-- Google Adsense -->
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
        (adsbygoogle = window.adsbygoogle || []).push({
            google_ad_client: "ca-pub-5419541141241701",
            enable_page_level_ads: true
        });
    </script>
    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
        <!-- Normal -->
        <ins class="adsbygoogle"
            style="display:block"
            data-ad-client="ca-pub-5419541141241701"
            data-ad-slot="1814399841"
            data-ad-format="auto"
            data-full-width-responsive="true"></ins>
        <script>
        (adsbygoogle = window.adsbygoogle || []).push({});
    </script>

    <!-- Vue.js -->
    <!-- <script src="https://cdn.jsdelivr.net/npm/vue"></script> -->

    <!-- コードハイライトライブラリ -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/8.6/styles/vs.min.css">
    <script src="../../../../lib/highlight.pack.js"></script>    
    <script>hljs.initHighlightingOnLoad();</script>
    
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0">
    <meta name="google-site-verification" content="09hfklx0xyk42C60Ah0xvRFySTBGutqeAlcYIgZrI9A" />
    <meta name="keywords" content="F,F#,Ｆ＃,Ｆ,FSharp,F-Sharp,try,finally,例外処理,Midoliy">

    <title>Midoliy |> F# - try...finally式</title>

    <!-- CSS -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.1/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link rel="stylesheet" href="../../../../css/text-page.css?20190311/">

</head>

<body>
    <header>
        <div class="icon">
            <a href="../../index.html" title="F#-TOPへ">
                <div>try...finally式</div>
            </a>
            <div>Midoliy｜F#プログラミング</div>
        </div>
    </header>

    <section>
        <!-- index-column -->
        <div class="content-list">
            <div><a href="#try...finally式の概要" class="section-title"><b> try...finally式の概要</b></a></div>
            <div><a href="#サンプルでみるtry...finally式" class="section-title"><b> サンプルでみるtry...finally式</b></a></div>
        </div>
        
        <!-- content-column -->
        <div class="content">

            <!-- ---------------------- -->
            <!--  try...finally式の概要  -->
            <!-- ---------------------- -->
            <h1 id="try...finally式の概要" class="section-title"> try...finally式の概要</h1>
            <div>
                <br>
                
                　このトピックでは、F#で使用される例外処理のための式である<span class="keyword">try...finally式</span>を紹介します。<br>
                　try...finally式を使用すると、try句内で例外が発生した場合でもクリーンアップコードを実行することが可能です。<br>

                <pre class="code-font"><code class="fsharp">// ------------------
// [ 構文 ]
// ------------------
try
    trying-expressions
finally
    clean-up-expressions</code></pre>
                <br>

                　finally句に記述した処理は、try句が終了した後に必ず実行されます。「正常終了した」のか、「例外が発生した」のかは関係ありません。そのため、リソースの解放処理やクローズ処理などを記述するために使われることが多いです。また、finally句の戻り値は、式全体の戻り値に影響を与えません。例外が発生しないときに返される型は【trying-expressions】の値となります。もし、try句内で例外をキャッチしたい場合は、try...with式を入れ子にして記述します。try...with式を記述せずに例外が発生した場合は、finally句の処理が完了したあとに、例外が呼び出し元へと伝播していきます。<br>

                <br>
            </div>

            <br>
            
            <!-- ------------------------------ -->
            <!--  サンプルでみるtry...finally式  -->
            <!-- ------------------------------ -->
            <h1 id="サンプルでみるtry...finally式" class="section-title"> サンプルでみるtry...finally式</h1>
            <div>
                <br>

                　以下はtry...finally式の簡単な利用方法を示しています。<br>
                <br>

                <div class="code"><script src="https://gist.github.com/Midoliy/06bcede7dff22227ed166756d7d30294.js?file=exception6.fs"></script></script></div>
                <br>

                　また、try...finally式の中に入れ子でtry...with式を記述することで例外ハンドリングをすることができます。この場合、finally句内のコードは、try句・with句のどちらかが完了したあとに必ず実行しなければならない(または実行したい)共通の処理が記述されます。<br>
                <br>

                <div class="code"><script src="https://gist.github.com/Midoliy/06bcede7dff22227ed166756d7d30294.js?file=exception7.fs"></script></script></div>
                <br>

                <br>
            </div>

            <br>

            <br>
        </div>
    </section>

    <footer>
        投稿日 : 2019/03/17
    </footer>
</body>

</html>